### ISSUE TITLE
Access to fetch at 'https://xxxx.cloud.looker.com/api/4.0/queries/741/run/json_detail' from origin 'http://localhost:3000' has been blocked by CORS policy:

### ISSUE THREAD

**Issue by 3DGISKing** [looker-open-source/component-examples#7]
Dear, author,
I have just followed your tutorial but it does not work for me.

https://developers.looker.com/components/getting-started/

I see this error message.

Access to fetch at 'https://xxxx.cloud.looker.com/api/4.0/queries/741/run/json_detail' from origin 'http://localhost:3000' has been blocked by CORS policy:

I would be thankful if you give me any hint for this error

**Comment by fabio-looker** [comment]
Have you made sure to follow this section from the article:

### Configure CORS in your Looker instance

Cross-Origin Resource Sharing (CORS) is controlled by the same domain allowlist as embedding.

This is documented in more detail on the [Single Sign-on (SSO) Embedding](https://docs.looker.com/reference/embedding/sso-embed) documentation page.

Navigate to Admin > Platform Embed on your Looker instance. This requires Admin privileges.

The React app runs by default at http://localhost:3000. By adding this address to the [Embedded Domain Allowlist](https://docs.looker.com/admin-options/platform/embed#embedded_domain_allowlist) you are telling Looker to allow requests from the app and respond to those requests via the same address. This step is mandatory since the app will be making API requests to the Looker instance else there won’t be communication between Looker and the app.
